#ifndef CONFIG_H_
#define CONFIG_H_

#if defined(IDF_TARGET_ESP32) || defined(IDF_TARGET_ESP32S3)
#define ESP32
#endif // defined(IDF_TARGET_ESP32) || defined(IDF_TARGET_ESP32S3

#define SCTP_MTU CONFIG_LIBPEER_SCTP_MTU
#define CONFIG_MTU CONFIG_LIBPEER_CONFIG_MTU
#define RSA_KEY_LENGTH CONFIG_LIBPEER_RSA_KEY_LENGTH

#define VIDEO_RB_DATA_LENGTH (CONFIG_MTU * CONFIG_LIBPEER_VIDEO_RB_DATA_MTUS)
#define AUDIO_RB_DATA_LENGTH (CONFIG_MTU * CONFIG_LIBPEER_AUDIO_RB_DATA_MTUS)
#define DATA_RB_DATA_LENGTH  (SCTP_MTU * CONFIG_LIBPEER_DATA_RB_DATA_MTUS)

#define AUDIO_LATENCY CONFIG_LIBPEER_AUDIO_LATENCY_MS
#define KEEPALIVE_CONNCHECK CONFIG_LIBPEER_KEEPALIVE_CONNCHECK

#ifdef CONFIG_LIBPEER_IPV6
#define CONFIG_IPV6 1
#else  // CONFIG_LIBPEER_IPV6
#define CONFIG_IPV6 0
#endif // CONFIG_LIBPEER_IPV6

#define CONFIG_IFACE_PREFIX CONFIG_LIBPEER_IFACE_PREFIX

#ifdef CONFIG_LIBPEER_LOG_LEVEL_ERROR
#define LOG_LEVEL LEVEL_ERROR
#endif // CONFIG_LIBPEER_LOG_LEVEL_ERROR
#ifdef CONFIG_LIBPEER_LOG_LEVEL_WARN
#define LOG_LEVEL LEVEL_WARN
#endif // CONFIG_LIBPEER_LOG_LEVEL_WARN
#ifdef CONFIG_LIBPEER_LOG_LEVEL_INFO
#define LOG_LEVEL LEVEL_INFO
#endif // CONFIG_LIBPEER_LOG_LEVEL_INFO
#ifdef CONFIG_LIBPEER_LOG_LEVEL_DEBUG
#define LOG_LEVEL LEVEL_DEBUG
#endif // CONFIG_LIBPEER_LOG_LEVEL_DEBUG

#define LOG_REDIRECT CONFIG_LIBPEER_LOG_REDIRECT

#ifdef CONFIG_LIBPEER_DISABLE_PEER_SIGNALING
#define DISABLE_PEER_SIGNALING 1
#else  // CONFIG_LIBPEER_DISABLE_PEER_SIGNALING
#define DISABLE_PEER_SIGNALING 0
#endif // CONFIG_LIBPEER_DISABLE_PEER_SIGNALING

#endif  // CONFIG_H_
